#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 20 10:13:22 2022

@author: camillewathne
"""

import geopandas as gpd
import pandas as pd

neighborhood_shp = gpd.read_file("shapefile_neighborhoods.zip")
neighborhood_shp.columns = neighborhood_shp.columns.str.replace(' ', '')
neighborhood_shp = neighborhood_shp[["fid", "color_2", "name", "geodata_eg", "pop_chng",
                                    "hh_chng", "avehhsize", "shape_stle", "SHAPE__Len",
                                    "SHAPE__Are", "geometry"]]

neighborhood_shp = neighborhood_shp.rename(columns={"name":"Neighborhood"})
neighborhood_shp["Neighborhood"] = neighborhood_shp["Neighborhood"].str.strip()
neighborhood_shp["Neighborhood"] = neighborhood_shp["Neighborhood"].str.upper()

neighborhood_csv = pd.read_csv("neighborhood_data.csv")

combined_shp = neighborhood_shp.merge(neighborhood_csv, on=["Neighborhood"], how='outer', indicator=True)
print("\nMerge counts:\n\n", combined_shp["_merge"].value_counts() )
combined_shp = combined_shp.drop(columns="_merge")
combined_shp = combined_shp.set_index("Neighborhood")
combined_shp.columns = combined_shp.columns.str.replace(' ', '')
combined_shp = combined_shp.drop(columns="Unnamed:0")

combined_shp["per_anyprog"] = combined_shp["AnyProgram"] / combined_shp["TotalParcels"]
combined_shp["per_VAC"] = combined_shp["VAC:PROG"] / combined_shp["TotalParcels"]
combined_shp["per_REC"] = combined_shp["REC:PROG"] / combined_shp["TotalParcels"]
combined_shp["per_ADOPT"] = combined_shp["ADOPT:PROG"] / combined_shp["TotalParcels"]
combined_shp["per_BID"] = combined_shp["BID:PROG"] / combined_shp["TotalParcels"]
combined_shp["per_CityOwnedProg"] = combined_shp["CityOwnedProgramSubset"] / combined_shp["TotalParcels"]

combined_shp["per_white"] = combined_shp["white"] / combined_shp["population"]
combined_shp["per_black"] = combined_shp["blk_afam"] / combined_shp["population"]

combined_shp["per_popchange"] = combined_shp["pop_chng_y"] / combined_shp["population"]

combined_shp.to_file("combined_shp.gpkg",layer="Neighborhood")



